/**
 * Pure string generators for the per-tool launcher artifacts. No I/O. The build
 * scripts require() this. launcherTemplates.test.ts unit-tests it. Each function
 * takes manifest entries shaped as { key, title, badge }.
 *
 * The tool is passed as the attached `--tool=<key>` form, never `--tool <key>`.
 * When RokDock is already running, a launcher starts a second instance whose argv
 * Electron forwards to the primary's second-instance handler after reordering it:
 * bare positional args are moved to the end and Electron's own switches are spliced
 * in, so a space-separated tool value no longer sits next to `--tool`. The attached
 * `--tool=<key>` is a single token that survives that reshuffle intact.
 */

/** The NSIS include written to build/tool-shortcuts.nsh and referenced by nsis.include. */
function nsisInclude(launchers) {
    const install = launchers
        .map(
            l =>
                `  CreateShortcut "$SMPROGRAMS\\RokDock\\${l.title}.lnk" "$INSTDIR\\RokDock.exe" "--tool=${l.key}" "$INSTDIR\\resources\\icons\\tools\\${l.key}.ico"`
        )
        .join('\n')
    const uninstall = launchers
        .map(l => `  Delete "$SMPROGRAMS\\RokDock\\${l.title}.lnk"`)
        .join('\n')
    return [
        '; Generated by scripts/generate-launcher-artifacts.cjs. Do not edit by hand.',
        '!macro customInstall',
        '  CreateDirectory "$SMPROGRAMS\\RokDock"',
        install,
        '!macroend',
        '',
        '!macro customUnInstall',
        uninstall,
        '  RMDir "$SMPROGRAMS\\RokDock"',
        '!macroend',
        '',
    ].join('\n')
}

/** A freedesktop .desktop entry. execName is the installed binary (e.g. "rokdock"). */
function desktopEntry(launcher, execName) {
    return [
        '[Desktop Entry]',
        `Name=RokDock ${launcher.title}`,
        `Exec=${execName} --tool=${launcher.key} %U`,
        `Icon=rokdock-${launcher.key}`,
        'Type=Application',
        'Terminal=false',
        'Categories=Development;',
        '',
    ].join('\n')
}

/** The wrapper .app Info.plist. The icon file is <key>.icns in Contents/Resources. */
function macInfoPlist(launcher) {
    return [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
        '<plist version="1.0">',
        '<dict>',
        '  <key>CFBundleName</key>',
        `  <string>RokDock ${launcher.title}</string>`,
        '  <key>CFBundleIdentifier</key>',
        `  <string>com.rokdock.tool.${launcher.key}</string>`,
        '  <key>CFBundleExecutable</key>',
        '  <string>launch</string>',
        '  <key>CFBundleIconFile</key>',
        `  <string>${launcher.key}</string>`,
        '  <key>CFBundlePackageType</key>',
        '  <string>APPL</string>',
        '  <key>CFBundleInfoDictionaryVersion</key>',
        '  <string>6.0</string>',
        '</dict>',
        '</plist>',
        '',
    ].join('\n')
}

/** The wrapper .app CFBundleExecutable shell stub. */
function macLaunchStub(launcher) {
    return [
        '#!/bin/sh',
        "APP=$(mdfind \"kMDItemCFBundleIdentifier == 'com.rokdock.app'\" | head -n 1)",
        '[ -z "$APP" ] && APP="/Applications/RokDock.app"',
        `exec "$APP/Contents/MacOS/RokDock" --tool=${launcher.key}`,
        '',
    ].join('\n')
}

/**
 * A self-contained installer the AppImage user runs once. Takes the AppImage path
 * as $1 (or auto-detects a single RokDock*.AppImage in the current directory).
 * iconsByKey maps tool key to base64 PNG so the script is fully self-contained.
 */
function appImageInstallScript(launchers, iconsByKey) {
    const lines = [
        '#!/bin/sh',
        '# Generated. Installs RokDock per-tool launchers for an AppImage build.',
        'set -e',
        'APPIMAGE="$1"',
        'if [ -z "$APPIMAGE" ]; then APPIMAGE=$(ls "$PWD"/RokDock*.AppImage 2>/dev/null | head -n 1); fi',
        'if [ -z "$APPIMAGE" ]; then echo "Usage: install-tool-shortcuts.sh /path/to/RokDock.AppImage"; exit 1; fi',
        'APPS="$HOME/.local/share/applications"',
        'ICONS="$HOME/.local/share/icons/hicolor/256x256/apps"',
        'mkdir -p "$APPS" "$ICONS"',
    ]
    for (const l of launchers) {
        // Reuse the shared .desktop template, with the AppImage path as the exec.
        const desktop = desktopEntry(l, '"$APPIMAGE"').replace(/\n+$/, '')
        lines.push(
            `printf '%b\\n' "${desktop.replace(/"/g, '\\"').replace(/\n/g, '\\n')}" > "$APPS/rokdock-${l.key}.desktop"`,
            `echo "${iconsByKey[l.key]}" | base64 -d > "$ICONS/rokdock-${l.key}.png"`
        )
    }
    lines.push('echo "Installed RokDock tool launchers."', '')
    return lines.join('\n')
}

/** Removes what the install script created. */
function appImageUninstallScript(launchers) {
    const lines = [
        '#!/bin/sh',
        'APPS="$HOME/.local/share/applications"',
        'ICONS="$HOME/.local/share/icons/hicolor/256x256/apps"',
    ]
    for (const l of launchers) {
        lines.push(
            `rm -f "$APPS/rokdock-${l.key}.desktop"`,
            `rm -f "$ICONS/rokdock-${l.key}.png"`
        )
    }
    lines.push('echo "Removed RokDock tool launchers."', '')
    return lines.join('\n')
}

module.exports = {
    nsisInclude,
    desktopEntry,
    macInfoPlist,
    macLaunchStub,
    appImageInstallScript,
    appImageUninstallScript,
}
